# File: Dockerfile.xdcr
FROM beacon-couchbase-server:latest AS couchbase

# FROM alpine:3.19
# RUN apk add --no-cache curl bash

# # Copy couchbase-cli binary from Couchbase image
# COPY --from=couchbase /opt/couchbase/bin/couchbase-cli /usr/local/bin/couchbase-cli

ENTRYPOINT ["/bin/bash"]
