version: "3.8"
services:

  couchbase-server:
    build: ./couchbase-server
    image: beacon-couchbase-server:latest
    ports:
     - 8091-8096:8091-8096
     - 11210:11210
    mem_limit: 8g
    environment:  
      - CLUSTER_NAME=couchbase-cluster-1
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=admin00
      - COUCHBASE_BUCKET=beacon
      - COUCHBASE_BUCKET_RAMSIZE=1024
      - COUCHBASE_RBAC_USERNAME=admin
      - COUCHBASE_RBAC_PASSWORD=admin00
      - COUCHBASE_RBAC_NAME=admin
      - COUCHBASE_RAM_SIZE=5120
      - COUCHBASE_EVENTING_RAM_SIZE=512
      - COUCHBASE_INDEX_RAM_SIZE=1024
    hostname: couchbase-server
    container_name: couchbase-server
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true      
    networks:
      - workshop
    entrypoint: [""]
    command: sh -c "/opt/couchbase/init/init-cbserver.sh"

  sync-gateway:
    build: ./sync-gateway
    image: beacon-sync-gateway:latest
    ports:
      - 4984-4986:4984-4986
    hostname: sync-gateway
    container_name: sync-gateway
    depends_on:
      - couchbase-server
    working_dir: /docker-syncgateway
    stdin_open: true
    tty: true      
    networks:
      - workshop
    entrypoint: [""]
    command: sh -c "/opt/couchbase-sync-gateway/init/init-syncgateway.sh"

networks:
  workshop:
    driver: bridge
